2022-05-04 11:48:28.006 - INFO - 5040 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 11:48:28.028 - INFO - 5040 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 11:48:34.421 - INFO - 5040 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetBestChild
2022-05-04 11:48:34.473 - INFO - 5040 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2022-05-04 11:48:35.005 - INFO - 5040 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2022-05-04 11:48:36.769 - CRITICAL - 5040 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 854, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2022-05-04 11:48:36.769 - INFO - 5040 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=1763.59[ms]
2022-05-04 11:48:36.769 - CRITICAL - 5040 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 803, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 854, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2022-05-04 11:48:36.769 - INFO - 5040 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=2295.47[ms]
2022-05-04 11:48:36.769 - CRITICAL - 5040 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 639, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 803, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 854, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2022-05-04 11:48:36.777 - INFO - 5040 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetBestChild, HowEnded=Failure, Duration=2355.47[ms]
2022-05-04 14:11:18.219 - INFO - 9704 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:11:18.221 - INFO - 9704 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 14:11:35.826 - INFO - 9704 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:11:35.826 - INFO - 9704 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 14:19:16.851 - INFO - 17740 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:19:16.851 - INFO - 17740 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 14:22:55.158 - INFO - 9704 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:22:55.158 - INFO - 9704 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 14:24:42.725 - INFO - 9704 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:24:42.727 - INFO - 9704 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 14:28:22.749 - INFO - 17740 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 14:28:22.749 - INFO - 17740 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 15:22:21.439 - INFO - 18700 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 15:22:21.453 - INFO - 18700 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
2022-05-04 15:27:10.537 - INFO - 8188 - azureml.train.automl._local_managed_utils.is_docker_installed:354 - Docker is installed with Docker version 20.10.11, build dea9396
.
2022-05-04 15:27:10.545 - INFO - 8188 - azureml.train.automl.automlconfig._start_execution:222 - Submitting remote.
